### ISSUE TITLE
Tip Tab 2.7 not working as expected with Tab-less 0.5.2

### ISSUE THREAD

**Issue by grahamperrin** [iainbeeston/tab-less#13]
https://addons.mozilla.org/addon/tip-tab/

With a preference for Tip Tab to **not** open in a new window, Tab-less does (as expected) open the tab of Tip Tab in a new window. 

However: if the window of Tip Tab is left open, then (in any other window) a click on the Tip Tab icon will bring to front: 

- the window in which the Tip Tab tab _originated_

– not the Tip Tab window. 

Can you imagine a workaround for this issue on the Tab-less side? Or would it be something for the developer of Tip Tab to consider, as an enhancement? 

### Environment

Firefox 62.0 (64-bit) on FreeBSD-CURRENT. 

----

Side note: 

- Mozilla bug [1332447 - API to hide the tabstrip](https://bugzilla.mozilla.org/show_bug.cgi?id=1332447)

– and whilst that bug is not fixed, the `userChrome.css` workaround at <https://superuser.com/a/1268734>.

**Comment by iainbeeston** [comment]
Can I just repeat what you said in my own words, to see if I've understood the issue correctly?

With tab-less and tip tab working together, when you press the tip tab button in the address bar (from window A), it opens tip tab in a new window (let's call that window B) instead of in a new tab. Then if you don't close the tip tab window, and press the tip tab button again (let's say from a new window, window C), the tip tab window (window B) should come to the front, but instead the window that you first pressed the tip tab button on (window A) comes to the front?

Is that correct?

**Comment by grahamperrin** [comment]
Correct, exactly.

**Comment by iainbeeston** [comment]
I must admit, it sounds like an issue with Tip Tab: Tab-Less correctly opens Tip Tab in a new window the first time, but when you click Tip Tab again, Tab-Less wouldn't get involved. I suspect that Tip Tab records which window it was first opened in, and re-focuses that when you click the Tip Tab button. But in this situation Tip Tab has been pulled off into a new window, and so the wrong window is focused.

You could test this theory by:

1. Disabling Tab-Less
2. Press the Tip Tab button to open Tip Tab
3. Drag the Tip Tab tab out of it's window, so it's in a new Window by itself
4. Focus on another window or continue browsing
5. Press the Tip Tab button again

If I'm correct, Tip Tab will now focus on the window that opened Tip Tab tab the first time, not the new Tip Tap window, and it's a bug with Tip Tab.
